# Generated by Django 4.0.4 on 2022-05-04 09:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 9, 16, 19, 669707, tzinfo=utc)),
        ),
    ]
